# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

def shared
  # Lint
  pod 'SwiftLint'
end

target 'NotEnoughProduction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared
end
